version: 2

updates:
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    directory: "/"
    labels: [ '🛡️ Infrastructure / CI', 'skip-changelog' ]
    commit-message:
      prefix: "ci"